AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GlobalVarTest:
    Type: String
    Default: globaldefault
    Description: Hoe werkt dit met sam local start-api?

Resources:
  FunctieNaamHier:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./dist
      Runtime: go1.x
      Environment:
        Variables:
          TEST: default
          GLOBAL: 
            Ref: GlobalVarTest
      Events:
        BikesResource:
          Type: Api
          Properties:
            Method: any
            Path: '/'
        BikesResourceSub:
          Type: Api
          Properties:
            Method: any
            Path: '/{proxy+}'
        

